/**
 * Generates src/data/handStrength.json: hot-and-cold equity of each of the 169
 * starting hands against a single random hand.
 *
 * This is DERIVED data, not authored data. It is regenerated by
 * `npm run generate:handstrength` and spot-checked by test/tableScaling.test.ts
 * against fresh engine runs, so it can never silently drift from the engine.
 *
 * It is used only to break ties WITHIN a chart tier when a range is trimmed for
 * table size. Equity against a random hand is a known-imperfect proxy for
 * open-raising value (it undervalues suited connectors and overvalues small
 * pairs), which is exactly why the chart tier dominates the ordering and this
 * only settles ties.
 */
import { writeFileSync } from 'node:fs';
import { computeEquity } from '../src/engine/equity.ts';
import { Range, HAND_GRID, combosOfHandKey, comboCards } from '../src/engine/ranges.ts';
import { createRng, codeToString } from '../src/engine/deck.ts';

const ITERATIONS = 400_000;
const keys = HAND_GRID.flat();
const out = {};
const started = Date.now();

keys.forEach((key, i) => {
  // Any combo of a hand key has the same equity against a random hand by symmetry.
  const combo = combosOfHandKey(key)[0];
  const hole = comboCards(combo);
  const result = computeEquity({
    hole,
    opponents: [Range.full()],
    rng: createRng(`handstrength:${key}`),
    iterations: ITERATIONS,
    targetStandardError: 0,
    maxIterations: ITERATIONS,
  });
  out[key] = Math.round(result.equity * 100) / 100;
  if ((i + 1) % 20 === 0) {
    process.stderr.write(`  ${i + 1}/${keys.length} (${Math.round((Date.now() - started) / 1000)}s)\n`);
  }
});

const sorted = Object.entries(out).sort((a, b) => b[1] - a[1]);
writeFileSync('src/data/handStrength.json', JSON.stringify({
  meta: {
    description: 'Hot-and-cold equity (%) of each starting hand against one random hand, all five board cards dealt.',
    generatedBy: 'scripts/generateHandStrength.mjs',
    iterations: ITERATIONS,
    method: 'Monte Carlo, seeded per hand as handstrength:<key>. Regenerate with npm run generate:handstrength.',
    note: 'DERIVED data. Used only to break ties within a chart tier when scaling ranges for table size.',
  },
  equityVsRandom: Object.fromEntries(sorted),
}, null, 2) + '\n');

console.log(`Wrote 169 hands in ${Math.round((Date.now() - started) / 1000)}s`);
console.log('Strongest:', sorted.slice(0, 5).map(([k, v]) => `${k} ${v}%`).join('  '));
console.log('Weakest:  ', sorted.slice(-5).map(([k, v]) => `${k} ${v}%`).join('  '));
